# Build script for https://github.com/tarof429/complex.git
sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tarof429/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tarof429/react-test npm run test

after_success:
  - docker build -t tarof429/multi-client ./client
  - docker build -t tarof429/multi-nginx ./nginx
  - docker build -t tarof429/multi-server ./server
  - docker build -t tarof429/multi-worker ./worker
  # Login to docker-hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Push images to docker-hub
  - docker push tarof429/multi-client
  - docker push tarof429/multi-nginx
  - docker push tarof429/multi-server 
  - docker push tarof429/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
  region: "us-west-2"
  app: "complex"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-981150355971"
  bucket_path: "docker-multi"
  on:
    branch: master
