version: '3'
services:
    nginx:
      depends_on:
        - api
        - client
      restart: always
      build:
        context: ./nginx
        dockerfile: Dockerfile.dev
      ports:
        - '3050:80'
    postgres:
      image: postgres:latest
      environment:
        - POSTGRES_PASSWORD=postgres_password
    redis:
      image: redis:latest
    api:
      depends_on:
        - postgres
      build:
        context: ./server
        dockerfile: Dockerfile.dev
      volumes:
        -  /app/node_modules
        - ./server:/app
      ports:
          - '5000:5000'
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - PGUSER=postgres
        - PGHOST=postgres
        - PGDATABASE=postgres
        - PGPASSWORD=postgres_password
        - PGPORT=5432
    client:
      stdin_open: true
      build:
        context: ./client
        dockerfile: Dockerfile.dev
      volumes:
        -  /app/node_modules
        - ./client:/app
    worker:
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      build:
        context: ./worker
        dockerfile: Dockerfile.dev
      volumes:
        -  /app/node_modules
        - ./worker:/app
volumes:
  pgdata: